# yaml-language-server: $schema=https://raw.githubusercontent.com/rlch/scaf/main/.scaf-type.schema.json

models:
  Authored: {}
  Comment:
    fields:
      createdAt:
        type: int
        required: true
      id:
        type: int
        required: true
      text:
        type: string
        required: true
  Has: {}
  Post:
    fields:
      content:
        type: string
        required: true
      createdAt:
        type: int
        required: true
      id:
        type: int
        required: true
      title:
        type: string
        required: true
  Replies: {}
  User:
    fields:
      createdAt:
        type: int
        required: true
      email:
        type: string
        required: true
      id:
        type: int
        required: true
      name:
        type: string
        required: true
  Wrote: {}
