// Code generated by scaf. DO NOT EDIT.
//go:build !scaf_prod

package db

import (
	"context"
	"github.com/rlch/neogo"
)

func init() {
	getPostByIdImpl = getPostByIdMock
	getPostsByAuthorImpl = getPostsByAuthorMock
	countPostsImpl = countPostsMock
	countRelationshipsImpl = countRelationshipsMock
	createPostImpl = createPostMock
	updatePostImpl = updatePostMock
	deletePostImpl = deletePostMock
	listPostsImpl = listPostsMock
	getCommentByIdImpl = getCommentByIdMock
	getCommentsByPostImpl = getCommentsByPostMock
	getCommentsByUserImpl = getCommentsByUserMock
	countCommentsByPostImpl = countCommentsByPostMock
	createCommentImpl = createCommentMock
	updateCommentImpl = updateCommentMock
	deleteCommentImpl = deleteCommentMock
}

func getPostByIdMock(ctx context.Context, db neogo.Driver, id int) ([]*getPostByIdResult, error) {
	if id == 1 {
		return []*getPostByIdResult{{
			ID: 0,
			Title: "Hello World",
			Content: "",
			AuthorName: "Alice",
		}}, nil
	} else if id == 999 {
		return []*getPostByIdResult{{
			ID: nil,
			Title: nil,
			Content: "",
			AuthorName: "",
		}}, nil
	}
	panic("no matching test case")
}

func getPostsByAuthorMock(ctx context.Context, db neogo.Driver, authorId int) ([]*getPostsByAuthorResult, error) {
	if authorId == 1 {
		return []*getPostsByAuthorResult{{
			ID: 0,
			Title: "Learning Neo4j",
			Content: "",
		}}, nil
	} else if authorId == 2 {
		return []*getPostsByAuthorResult{{
			ID: 0,
			Title: "Bob's Post",
			Content: "",
		}}, nil
	}
	panic("no matching test case")
}

func countPostsMock(ctx context.Context, db neogo.Driver) ([]int, error) {
	if true {
		return []int{3}, nil
	}
	panic("no matching test case")
}

func countRelationshipsMock(ctx context.Context, db neogo.Driver) ([]int, error) {
	if true {
		return []int{3}, nil
	}
	panic("no matching test case")
}

func createPostMock(ctx context.Context, db neogo.Driver, authorId int, id int, title string, content string, createdAt int) ([]*createPostResult, error) {
	if authorId == 1 && id == 10 && title == "New Post" && content == "Some content here" && createdAt == 1700001000 {
		return []*createPostResult{{
			ID: 10,
			Title: "New Post",
			Content: "",
		}}, nil
	}
	panic("no matching test case")
}

func updatePostMock(ctx context.Context, db neogo.Driver, id int, title string, content string) ([]*updatePostResult, error) {
	if id == 1 && title == "Hello World (Updated)" && content == "Updated content" {
		return []*updatePostResult{{
			ID: 0,
			Title: "Hello World (Updated)",
			Content: "Updated content",
		}}, nil
	}
	panic("no matching test case")
}

func deletePostMock(ctx context.Context, db neogo.Driver, id int) ([]int, error) {
	if id == 3 {
		return []int{1}, nil
	}
	panic("no matching test case")
}

func listPostsMock(ctx context.Context, db neogo.Driver) ([]*listPostsResult, error) {
	if true {
		return []*listPostsResult{{
			ID: 0,
			Title: "Bob's Post",
			AuthorName: "Bob",
		}}, nil
	}
	panic("no matching test case")
}

func getCommentByIdMock(ctx context.Context, db neogo.Driver, id int) ([]*getCommentByIdResult, error) {
	if id == 1 {
		return []*getCommentByIdResult{{
			ID: 0,
			Text: "Great post!",
			AuthorName: "Bob",
			PostTitle: "Hello World",
		}}, nil
	} else if id == 999 {
		return []*getCommentByIdResult{{
			ID: nil,
			Text: nil,
			AuthorName: "",
			PostTitle: "",
		}}, nil
	}
	panic("no matching test case")
}

func getCommentsByPostMock(ctx context.Context, db neogo.Driver, postId int) ([]*getCommentsByPostResult, error) {
	if postId == 1 {
		return []*getCommentsByPostResult{{
			ID: 0,
			Text: "Great post!",
			AuthorName: "Bob",
		}}, nil
	}
	panic("no matching test case")
}

func getCommentsByUserMock(ctx context.Context, db neogo.Driver, userId int) ([]*getCommentsByUserResult, error) {
	if userId == 2 {
		return []*getCommentsByUserResult{{
			ID: 0,
			Text: "I agree!",
			PostTitle: "",
		}}, nil
	} else if userId == 1 {
		return []*getCommentsByUserResult{{
			ID: 0,
			Text: "Thanks for sharing",
			PostTitle: "",
		}}, nil
	}
	panic("no matching test case")
}

func countCommentsByPostMock(ctx context.Context, db neogo.Driver, postId int) ([]int, error) {
	if postId == 1 {
		return []int{3}, nil
	}
	panic("no matching test case")
}

func createCommentMock(ctx context.Context, db neogo.Driver, authorId int, postId int, id int, text string, createdAt int) ([]*createCommentResult, error) {
	if authorId == 1 && postId == 1 && id == 10 && text == "New comment" && createdAt == 1700001000 {
		return []*createCommentResult{{
			ID: 10,
			Text: "New comment",
		}}, nil
	}
	panic("no matching test case")
}

func updateCommentMock(ctx context.Context, db neogo.Driver, id int, text string) ([]*updateCommentResult, error) {
	if id == 1 && text == "Updated comment!" {
		return []*updateCommentResult{{
			ID: 0,
			Text: "Updated comment!",
		}}, nil
	}
	panic("no matching test case")
}

func deleteCommentMock(ctx context.Context, db neogo.Driver, id int) ([]int, error) {
	if id == 3 {
		return []int{1}, nil
	}
	panic("no matching test case")
}
