// Code generated by scaf. DO NOT EDIT.
//go:build !scaf_prod

package db

import (
	"context"
	"github.com/rlch/neogo"
)

func init() {
	getCommentByIdImpl = getCommentByIdMock
	getCommentsByPostImpl = getCommentsByPostMock
	getCommentsByUserImpl = getCommentsByUserMock
	countCommentsByPostImpl = countCommentsByPostMock
	createCommentImpl = createCommentMock
	updateCommentImpl = updateCommentMock
	deleteCommentImpl = deleteCommentMock
	getPostByIdImpl = getPostByIdMock
	getPostsByAuthorImpl = getPostsByAuthorMock
	countPostsImpl = countPostsMock
	countRelationshipsImpl = countRelationshipsMock
	createPostImpl = createPostMock
	updatePostImpl = updatePostMock
	deletePostImpl = deletePostMock
	listPostsImpl = listPostsMock
	getUserByIdImpl = getUserByIdMock
	getUserByEmailImpl = getUserByEmailMock
	countUsersImpl = countUsersMock
	createUserImpl = createUserMock
	updateUserImpl = updateUserMock
	deleteUserImpl = deleteUserMock
	listUsersImpl = listUsersMock
}

func getCommentByIdMock(ctx context.Context, db neogo.Driver, id int) ([]*getCommentByIdResult, error) {
	if id == 1 {
		return []*getCommentByIdResult{{
			ID: 0,
			Text: "Great post!",
			AuthorName: "Bob",
			PostTitle: "Hello World",
		}}, nil
	} else if id == 999 {
		return []*getCommentByIdResult{{
			ID: 0,
			Text: "",
			AuthorName: "",
			PostTitle: "",
		}}, nil
	}
	panic("no matching test case")
}

func getCommentsByPostMock(ctx context.Context, db neogo.Driver, postId int) ([]*getCommentsByPostResult, error) {
	if postId == 1 {
		return []*getCommentsByPostResult{{
			ID: 0,
			Text: "Great post!",
			AuthorName: "Bob",
		}}, nil
	}
	panic("no matching test case")
}

func getCommentsByUserMock(ctx context.Context, db neogo.Driver, userId int) ([]*getCommentsByUserResult, error) {
	if userId == 2 {
		return []*getCommentsByUserResult{{
			ID: 0,
			Text: "I agree!",
			PostTitle: "",
		}}, nil
	} else if userId == 1 {
		return []*getCommentsByUserResult{{
			ID: 0,
			Text: "Thanks for sharing",
			PostTitle: "",
		}}, nil
	}
	panic("no matching test case")
}

func countCommentsByPostMock(ctx context.Context, db neogo.Driver, postId int) ([]int, error) {
	if postId == 1 {
		return []int{3}, nil
	}
	panic("no matching test case")
}

func createCommentMock(ctx context.Context, db neogo.Driver, authorId int, postId int, id int, text string, createdAt int) ([]*createCommentResult, error) {
	if authorId == 1 && postId == 1 && id == 10 && text == "New comment" && createdAt == 1700001000 {
		return []*createCommentResult{{
			ID: 10,
			Text: "New comment",
		}}, nil
	}
	panic("no matching test case")
}

func updateCommentMock(ctx context.Context, db neogo.Driver, id int, text string) ([]*updateCommentResult, error) {
	if id == 1 && text == "Updated comment!" {
		return []*updateCommentResult{{
			ID: 0,
			Text: "Updated comment!",
		}}, nil
	}
	panic("no matching test case")
}

func deleteCommentMock(ctx context.Context, db neogo.Driver, id int) ([]int, error) {
	if id == 3 {
		return []int{1}, nil
	}
	panic("no matching test case")
}

func getPostByIdMock(ctx context.Context, db neogo.Driver, id int) ([]*getPostByIdResult, error) {
	if id == 1 {
		return []*getPostByIdResult{{
			ID: 0,
			Title: "Hello World",
			Content: "",
			AuthorName: "Alice",
		}}, nil
	} else if id == 999 {
		return []*getPostByIdResult{{
			ID: 0,
			Title: "",
			Content: "",
			AuthorName: "",
		}}, nil
	}
	panic("no matching test case")
}

func getPostsByAuthorMock(ctx context.Context, db neogo.Driver, authorId int) ([]*getPostsByAuthorResult, error) {
	if authorId == 1 {
		return []*getPostsByAuthorResult{{
			ID: 0,
			Title: "Learning Neo4j",
			Content: "",
		}}, nil
	} else if authorId == 2 {
		return []*getPostsByAuthorResult{{
			ID: 0,
			Title: "Bob's Post",
			Content: "",
		}}, nil
	}
	panic("no matching test case")
}

func countPostsMock(ctx context.Context, db neogo.Driver) ([]int, error) {
	if true {
		return []int{3}, nil
	}
	panic("no matching test case")
}

func countRelationshipsMock(ctx context.Context, db neogo.Driver) ([]int, error) {
	if true {
		return []int{3}, nil
	}
	panic("no matching test case")
}

func createPostMock(ctx context.Context, db neogo.Driver, authorId int, id int, title string, content string, createdAt int) ([]*createPostResult, error) {
	if authorId == 1 && id == 10 && title == "New Post" && content == "Some content here" && createdAt == 1700001000 {
		return []*createPostResult{{
			ID: 10,
			Title: "New Post",
			Content: "",
		}}, nil
	}
	panic("no matching test case")
}

func updatePostMock(ctx context.Context, db neogo.Driver, id int, title string, content string) ([]*updatePostResult, error) {
	if id == 1 && title == "Hello World (Updated)" && content == "Updated content" {
		return []*updatePostResult{{
			ID: 0,
			Title: "Hello World (Updated)",
			Content: "Updated content",
		}}, nil
	}
	panic("no matching test case")
}

func deletePostMock(ctx context.Context, db neogo.Driver, id int) ([]int, error) {
	if id == 3 {
		return []int{1}, nil
	}
	panic("no matching test case")
}

func listPostsMock(ctx context.Context, db neogo.Driver) ([]*listPostsResult, error) {
	if true {
		return []*listPostsResult{{
			ID: 0,
			Title: "Bob's Post",
			AuthorName: "Bob",
		}}, nil
	}
	panic("no matching test case")
}

func getUserByIdMock(ctx context.Context, db neogo.Driver, id int) ([]*getUserByIdResult, error) {
	if id == 1 {
		return []*getUserByIdResult{{
			ID: 0,
			Name: "Alice",
			Email: "alice@example.com",
			CreatedAt: 0,
		}}, nil
	} else if id == 2 {
		return []*getUserByIdResult{{
			ID: 0,
			Name: "Bob",
			Email: "bob@example.com",
			CreatedAt: 0,
		}}, nil
	} else if id == 999 {
		return []*getUserByIdResult{{
			ID: 0,
			Name: "",
			Email: "",
			CreatedAt: 0,
		}}, nil
	}
	panic("no matching test case")
}

func getUserByEmailMock(ctx context.Context, db neogo.Driver, email string) ([]*getUserByEmailResult, error) {
	if email == "alice@example.com" {
		return []*getUserByEmailResult{{
			ID: 1,
			Name: "Alice",
			Email: "",
		}}, nil
	} else if email == "nobody@example.com" {
		return []*getUserByEmailResult{{
			ID: 0,
			Name: "",
			Email: "",
		}}, nil
	}
	panic("no matching test case")
}

func countUsersMock(ctx context.Context, db neogo.Driver) ([]int, error) {
	if true {
		return []int{3}, nil
	}
	panic("no matching test case")
}

func createUserMock(ctx context.Context, db neogo.Driver, id int, name string, email string, createdAt int) ([]*createUserResult, error) {
	if id == 10 && name == "Dave" && email == "dave@example.com" && createdAt == 1700000010 {
		return []*createUserResult{{
			ID: 10,
			Name: "Dave",
			Email: "dave@example.com",
		}}, nil
	}
	panic("no matching test case")
}

func updateUserMock(ctx context.Context, db neogo.Driver, id int, name string, email string) ([]*updateUserResult, error) {
	if id == 1 && name == "Alice Smith" && email == "alice.smith@example.com" {
		return []*updateUserResult{{
			ID: 0,
			Name: "Alice Smith",
			Email: "alice.smith@example.com",
		}}, nil
	}
	panic("no matching test case")
}

func deleteUserMock(ctx context.Context, db neogo.Driver, id int) ([]int, error) {
	if id == 3 {
		return []int{1}, nil
	} else if id == 999 {
		return []int{0}, nil
	}
	panic("no matching test case")
}

func listUsersMock(ctx context.Context, db neogo.Driver) ([]*listUsersResult, error) {
	if true {
		return []*listUsersResult{{
			ID: 0,
			Name: "Charlie",
			Email: "",
		}}, nil
	}
	panic("no matching test case")
}
