// Code generated by scaf. DO NOT EDIT.
//go:build !scaf_prod

package basic

import (
	"context"
	"github.com/rlch/neogo"
)

func init() {
	getUserImpl = getUserMock
}

func getUserMock(ctx context.Context, db neogo.Driver, userId any) ([]*getUserResult, error) {
	if userId == 1 {
		return []*getUserResult{{
			Name: "Alice",
			Email: "alice@example.com",
		}}, nil
	} else if userId == 2 {
		return []*getUserResult{{
			Name: "Bob",
			Email: "bob@example.com",
		}}, nil
	} else if userId == 1 {
		return []*getUserResult{{
			Name: "Alice",
			Email: nil,
		}}, nil
	}
	panic("no matching test case")
}
