// Code generated by scaf. DO NOT EDIT.

package basic

import (
	"context"
	"github.com/rlch/neogo"
)

type getUserResult struct {
	Name any
	Email any
}

func GetUser(ctx context.Context, db neogo.Driver, userId any) ([]*getUserResult, error) {
	return getUserImpl(ctx, db, userId)
}

var getUserImpl func(context.Context, neogo.Driver, any) ([]*getUserResult, error) = getUserProd

func getUserProd(ctx context.Context, db neogo.Driver, userId any) ([]*getUserResult, error) {
	var rowsName []any
	var rowsEmail []any
	err := db.Exec().
		Cypher(`MATCH (u:User {id: $userId})
	RETURN u.name, u.email`).
		RunWithParams(ctx, map[string]any{"userId": userId}, "u.name", &rowsName, "u.email", &rowsEmail)
	if err != nil {
		return nil, err
	}
	results := make([]*getUserResult, len(rowsName))
	for i := range rowsName {
		results[i] = &getUserResult{
			Name: rowsName[i],
			Email: rowsEmail[i],
		}
	}
	return results, nil
}
