// Code generated by scaf. DO NOT EDIT.

package db

import (
	"context"
	"github.com/rlch/neogo"
)

func CreateUser(ctx context.Context, db neogo.Driver, id int, name string, email string, createdAt int) error {
	return createUserImpl(ctx, db, id, name, email, createdAt)
}

var createUserImpl func(context.Context, neogo.Driver, int, string, string, int) error = createUserProd

func createUserProd(ctx context.Context, db neogo.Driver, id int, name string, email string, createdAt int) error {
	err := db.Exec().
		Cypher(`CREATE (u:User {id: $id, name: $name, email: $email, createdAt: $createdAt})`).
		RunWithParams(ctx, map[string]any{"id": id, "name": name, "email": email, "createdAt": createdAt})
	if err != nil {
		return err
	}
	return nil
}

func CreateUsers(ctx context.Context, db neogo.Driver) error {
	return createUsersImpl(ctx, db)
}

var createUsersImpl func(context.Context, neogo.Driver) error = createUsersProd

func createUsersProd(ctx context.Context, db neogo.Driver) error {
	err := db.Exec().
		Cypher(`CREATE (alice:User {id: 1, name: "Alice", email: "alice@example.com", createdAt: 1700000000})
	CREATE (bob:User {id: 2, name: "Bob", email: "bob@example.com", createdAt: 1700000001})
	CREATE (charlie:User {id: 3, name: "Charlie", email: "charlie@example.com", createdAt: 1700000002})`).
		Run(ctx)
	if err != nil {
		return err
	}
	return nil
}

func CreatePost(ctx context.Context, db neogo.Driver, authorId int, id int, title string, content string, createdAt int) error {
	return createPostImpl(ctx, db, authorId, id, title, content, createdAt)
}

var createPostImpl func(context.Context, neogo.Driver, int, int, string, string, int) error = createPostProd

func createPostProd(ctx context.Context, db neogo.Driver, authorId int, id int, title string, content string, createdAt int) error {
	err := db.Exec().
		Cypher(`MATCH (u:User {id: $authorId})
	CREATE (p:Post {id: $id, title: $title, content: $content, createdAt: $createdAt})
	CREATE (u)-[:AUTHORED]->(p)`).
		RunWithParams(ctx, map[string]any{"authorId": authorId, "id": id, "title": title, "content": content, "createdAt": createdAt})
	if err != nil {
		return err
	}
	return nil
}

func CreatePosts(ctx context.Context, db neogo.Driver) error {
	return createPostsImpl(ctx, db)
}

var createPostsImpl func(context.Context, neogo.Driver) error = createPostsProd

func createPostsProd(ctx context.Context, db neogo.Driver) error {
	err := db.Exec().
		Cypher(`MATCH (alice:User {id: 1}), (bob:User {id: 2})
	CREATE (p1:Post {id: 1, title: "Hello World", content: "My first post!", createdAt: 1700000100})
	CREATE (p2:Post {id: 2, title: "Learning Neo4j", content: "Graph databases are cool", createdAt: 1700000200})
	CREATE (p3:Post {id: 3, title: "Bob's Post", content: "Hi from Bob", createdAt: 1700000300})
	CREATE (alice)-[:AUTHORED]->(p1)
	CREATE (alice)-[:AUTHORED]->(p2)
	CREATE (bob)-[:AUTHORED]->(p3)`).
		Run(ctx)
	if err != nil {
		return err
	}
	return nil
}

func CreateComment(ctx context.Context, db neogo.Driver, authorId int, postId int, id int, text string, createdAt int) error {
	return createCommentImpl(ctx, db, authorId, postId, id, text, createdAt)
}

var createCommentImpl func(context.Context, neogo.Driver, int, int, int, string, int) error = createCommentProd

func createCommentProd(ctx context.Context, db neogo.Driver, authorId int, postId int, id int, text string, createdAt int) error {
	err := db.Exec().
		Cypher(`MATCH (u:User {id: $authorId}), (p:Post {id: $postId})
	CREATE (c:Comment {id: $id, text: $text, createdAt: $createdAt})
	CREATE (u)-[:WROTE]->(c)
	CREATE (c)-[:ON_POST]->(p)`).
		RunWithParams(ctx, map[string]any{"authorId": authorId, "postId": postId, "id": id, "text": text, "createdAt": createdAt})
	if err != nil {
		return err
	}
	return nil
}

func CreateComments(ctx context.Context, db neogo.Driver) error {
	return createCommentsImpl(ctx, db)
}

var createCommentsImpl func(context.Context, neogo.Driver) error = createCommentsProd

func createCommentsProd(ctx context.Context, db neogo.Driver) error {
	err := db.Exec().
		Cypher(`MATCH (alice:User {id: 1}), (bob:User {id: 2}), (p1:Post {id: 1})
	CREATE (c1:Comment {id: 1, text: "Great post!", createdAt: 1700000150})
	CREATE (c2:Comment {id: 2, text: "Thanks for sharing", createdAt: 1700000160})
	CREATE (c3:Comment {id: 3, text: "I agree!", createdAt: 1700000170})
	CREATE (bob)-[:WROTE]->(c1)
	CREATE (alice)-[:WROTE]->(c2)
	CREATE (bob)-[:WROTE]->(c3)
	CREATE (c1)-[:ON_POST]->(p1)
	CREATE (c2)-[:ON_POST]->(p1)
	CREATE (c3)-[:ON_POST]->(p1)`).
		Run(ctx)
	if err != nil {
		return err
	}
	return nil
}
