# yaml-language-server: $schema=https://raw.githubusercontent.com/rlch/scaf/refs/heads/master/.scaf-type.schema.json

models:
  Authored: {}
  Comment:
    fields:
      createdAt:
        type: int
        required: true
      id:
        type: int
        required: true
      text:
        type: string
        required: true
    relationships:
      Replies:
        rel_type: REPLIES
        target: Comment
        many: true
        direction: outgoing
  Has: {}
  Post:
    fields:
      content:
        type: string
        required: true
      createdAt:
        type: int
        required: true
      id:
        type: int
        required: true
      title:
        type: string
        required: true
    relationships:
      Has:
        rel_type: HAS
        target: Comment
        many: true
        direction: outgoing
  Replies: {}
  User:
    fields:
      createdAt:
        type: int
        required: true
      email:
        type: string
        required: true
      id:
        type: int
        required: true
      name:
        type: string
        required: true
    relationships:
      Authored:
        rel_type: AUTHORED
        target: Post
        many: true
        direction: outgoing
      Wrote:
        rel_type: WROTE
        target: Comment
        many: true
        direction: outgoing
  Wrote: {}
