// Code generated by scaf. DO NOT EDIT.

package neogo

import (
	"context"
	"github.com/rlch/neogo"
)

type findActorsResult struct {
	Name any
	Title any
	Roles any
}

type findDirectorsResult struct {
	Name any
	Title any
}

type findReviewsResult struct {
	Name any
	Summary any
	Rating any
}

func FindActors(ctx context.Context, db neogo.Driver, name any) ([]*findActorsResult, error) {
	return findActorsImpl(ctx, db, name)
}

var findActorsImpl func(context.Context, neogo.Driver, any) ([]*findActorsResult, error) = findActorsProd

func findActorsProd(ctx context.Context, db neogo.Driver, name any) ([]*findActorsResult, error) {
	var rowsName []any
	var rowsTitle []any
	var rowsRoles []any
	err := db.Exec().
		Cypher(`MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
	  WHERE p.name = $name
	  RETURN p.name, m.title, r.roles`).
		RunWithParams(ctx, map[string]any{"name": name}, "p.name", &rowsName, "m.title", &rowsTitle, "r.roles", &rowsRoles)
	if err != nil {
		return nil, err
	}
	results := make([]*findActorsResult, len(rowsName))
	for i := range rowsName {
		results[i] = &findActorsResult{
			Name: rowsName[i],
			Title: rowsTitle[i],
			Roles: rowsRoles[i],
		}
	}
	return results, nil
}

func FindDirectors(ctx context.Context, db neogo.Driver) ([]*findDirectorsResult, error) {
	return findDirectorsImpl(ctx, db)
}

var findDirectorsImpl func(context.Context, neogo.Driver) ([]*findDirectorsResult, error) = findDirectorsProd

func findDirectorsProd(ctx context.Context, db neogo.Driver) ([]*findDirectorsResult, error) {
	var rowsName []any
	var rowsTitle []any
	err := db.Exec().
		Cypher(`MATCH (p:Person)-[:DIRECTED]->(m:Movie)
	  RETURN p.name, m.title`).
		Run(ctx, "p.name", &rowsName, "m.title", &rowsTitle)
	if err != nil {
		return nil, err
	}
	results := make([]*findDirectorsResult, len(rowsName))
	for i := range rowsName {
		results[i] = &findDirectorsResult{
			Name: rowsName[i],
			Title: rowsTitle[i],
		}
	}
	return results, nil
}

func FindReviews(ctx context.Context, db neogo.Driver, title any) ([]*findReviewsResult, error) {
	return findReviewsImpl(ctx, db, title)
}

var findReviewsImpl func(context.Context, neogo.Driver, any) ([]*findReviewsResult, error) = findReviewsProd

func findReviewsProd(ctx context.Context, db neogo.Driver, title any) ([]*findReviewsResult, error) {
	var rowsName []any
	var rowsSummary []any
	var rowsRating []any
	err := db.Exec().
		Cypher(`MATCH (p:Person)-[r:REVIEWED]->(m:Movie)
	  WHERE m.title = $title
	  RETURN p.name, r.summary, r.rating`).
		RunWithParams(ctx, map[string]any{"title": title}, "p.name", &rowsName, "r.summary", &rowsSummary, "r.rating", &rowsRating)
	if err != nil {
		return nil, err
	}
	results := make([]*findReviewsResult, len(rowsName))
	for i := range rowsName {
		results[i] = &findReviewsResult{
			Name: rowsName[i],
			Summary: rowsSummary[i],
			Rating: rowsRating[i],
		}
	}
	return results, nil
}
