# yaml-language-server: $schema=https://raw.githubusercontent.com/rlch/scaf/refs/heads/master/.scaf-type.schema.json

models:
  User:
    fields:
      id:
        type: int
        required: true
      name:
        type: string
        required: true
      email:
        type: string
